### ISSUE TITLE
 RDKit 

### ISSUE THREAD

**Issue by YavarYeganeh** [korakot/kora#13]
Recently, RDKit cannot be imported on Colab.

**Comment by EBjerrum** [comment]
I can confirm this issue. Google colab now uses python 3.7, but the kora rdkit installs for python 3.6

Check python version in Colab:
import sys
sys.version
OUT: 3.7.10 (default, Feb 20 2021, 21:17:23) \n[GCC 7.5.0]

Installation of RDKit is in python 3.6
!ls -d /usr/local/lib/python3.6/*/*
OUT: /usr/local/lib/python3.6/dist-packages/rdkit

A workaround until the gzipped rdkit install is fixed is to add the path with sys:
import sys
sys.path.append('/usr/local/lib/python3.6/dist-packages/')

but I'm not sure it will be entirely errorfree to mix python versions

**Comment by YavarYeganeh** [comment]
Thanks, it's working after adding the directory.

**Comment by korakot** [comment]
I have updated kora to use Python 3.7, and also use RDKit 2020.09.1

Please check if it works well with your case.

**Comment by YavarYeganeh** [comment]
> I have updated kora to use Python 3.7, and also use RDKit 2020.09.1
> 
> Please check if it works well with your case.

Thanks a lot. It now works very well again.

**Comment by EBjerrum** [comment]
Thanks for the update, kora makes life with Colab and RDKit so much easier :-)
