### ISSUE TITLE
python 3.9 in google colab?

### ISSUE THREAD

**Issue by brando90** [korakot/kora#21]
e.g.
```
!pip install kora
import kora.install.py39
```

https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory
https://github.com/korakot/kora/issues/21

**Comment by korakot** [comment]
I made an example notebook for Python 3.10 there already. (not using `kora`, though)

**Comment by j3soon** [comment]
Here's a version for Python 3.9 on Colab: https://colab.research.google.com/github/j3soon/colab-python-version/blob/main/notebooks/py39.ipynb , which is also not using `kora`, but using a similar technique as [the Python 3.10 and 3.11 examples](https://github.com/korakot/kora/releases).
