### ISSUE TITLE
I cant run google colab in Py310

### ISSUE THREAD

**Issue by hasanhut** [korakot/kora#27]
Hello, I take this code from stackoverflow.

!wget https://github.com/korakot/kora/releases/download/v0.10/py310.sh
!bash ./py310.sh -b -f -p /usr/local
!python -m ipykernel install --name "py310" --user

import sys
print("version:", sys.version)
OUTPUT = version: 3.8.16 (default, Dec  7 2022, 01:12:13) [GCC 7.5.0]

But when i write !python --version , it shows that Python3.10 version. How can I fix this situation. When I import a package, it imports it for python 3.8.

**Comment by korakot** [comment]
You cannot just run the code. You need to copy the notebook here

https://colab.research.google.com/drive/12Uy1fTJy4XQDMdXVM_5XJ0iGEdCDOgYf

This notebook is special. It specifies py310 as the kernel. If you just run the code, the code will install py310 kernel, but just use the same python3 kernel.

**Comment by hasanhut** [comment]
Thank you very much, now I understand.  so is there a notebook for python 3.7 version?

**Comment by korakot** [comment]
No. I only made the Python 3.10 and 3.11 versions.

**Comment by mrcreamio** [comment]
@korakot Can you guide me on how I can make one for 3.7?
