### ISSUE TITLE
neo4j

### ISSUE THREAD

**Issue by Btibert3** [korakot/kora#6]
I recieved the following error upon `from kora import neo`

```
ConnectionUnavailable: Cannot open connection to ConnectionProfile('bolt://neo4j@localhost:7687')
```

Perhaps I am not initializing neo4j the proper way.

**Comment by Btibert3** [comment]
Any ideas on how to attack this?

**Comment by korakot** [comment]
Somehow, the connection needs to be delayed. It is solved in the latest version.

**Comment by Btibert3** [comment]
Confirmed, thank you.  This project is amazing, and do reference it in my programming courses.
