### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by Btibert3** [korakot/kora#7]
When attempting:

```
from kora import console
console.start()
```

I get the following error on Colab

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-90b51bf2ab13> in <module>()
      1 # fire up a terminal hosted on top of Colab
      2 from kora import console
----> 3 console.start()

/usr/local/lib/python3.6/dist-packages/kora/console.py in start()
     24     for i in range(6):
     25         line = process.stdout.readline()
---> 26     url = line.decode().strip().split()[-1]
     27     print("Console URL:", url)
     28 

IndexError: list index out of range
```

**Comment by korakot** [comment]
I have tested, and now it works correctly. So, it's probably a temporary problem.

Please check if the problem still remains. I will close the issue for now.

**Comment by iamashwin99** [comment]
Even I have this error and is persistent in a session but occurs randomly. Is there a work around?

**Comment by korakot** [comment]
I have rewritten the code, so that it will print the teleconsole result when there is an error. 

I can't replicate the error. So, if you don't get `Console URL: https:..`, please report the error result here.
